server:
  port: 1314

spring:
  application:
    name: zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: https://eureka1.com:7001/eureka/
      #这是由于默认配置下eureka会把自己当成了客户端来注册自己。（在启动的时候，它会同时把自己当成客户端来注册自己。而在启动的过程中。它自己即使服务端又是客户端。服务端都还没启动好，客户端就去找肯定会报错！）
      # 所以我们需要禁用它的客户端默认的注册行为。在配置文件中加入：
    register-with-eureka: false
    fetch-registry: false


zuul:
    routes:
      api-a:
        serviceId: service-a
        path: /api-a/**
      api-b:
        serviceId: service-b
        path: /api-b/*
      api-c:
        serviceId: comput-service
        path: /api/**